### ISSUE TITLE
Stale version on rubygems.org

### ISSUE THREAD

**Issue by bencallaway** [judofyr/minitest-line#15]
I am working on a PR and cleaning up dependencies for https://github.com/trailblazer/roar-jsonapi which depends on minitest-line. The latest available version on rubygems.org is 0.6.3 which is from July 13, 2015. I am receiving warning messages in my test output that have since been resolved (e.g. d58faf50c186063ae1879f9411e0d5aeb0402bc4).

Could there be a new version (at least as new as d58faf) released to rubygems.org?

In any case thanks for putting work into this gem

**Comment by grosser** [comment]
@judofyr release it :D

**Comment by judofyr** [comment]
Pushed v0.6.4 now!
