### ISSUE TITLE
New version wanted

### ISSUE THREAD

**Issue by iNecas** [judofyr/minitest-line#9]
Hi,

Thank you for this nice gem. IMO the ability to track the specs is definitely something that deserves a new released version.

Thanks

**Comment by grosser** [comment]
ping @judofyr 

FYI in the meantime you can use [maxitest](https://github.com/grosser/maxitest) which bundles the latest minitest-line and a lot of other helpful tools/bugfixes

**Comment by judofyr** [comment]
Oh. Sure. I'll release it right away.

**Comment by judofyr** [comment]
Waiting for the build to complete: https://travis-ci.org/judofyr/minitest-line/builds/70786274

**Comment by judofyr** [comment]
Ugh. It failed. Trying to fix it: https://travis-ci.org/judofyr/minitest-line/builds/70789888

**Comment by judofyr** [comment]
Fifth time's a winner: https://travis-ci.org/judofyr/minitest-line/builds/70791212

**Comment by judofyr** [comment]
Aaaaand pushed!

https://rubygems.org/gems/minitest-line/versions/0.6.3
